module.exports = {
    1: "crvena",
    2: "zelena",
    3: "plava",
    4: "ljubicasta",
    5: "braon",
    6: "zuta",
    7: "narandzasta",
    8: "crna",

    9: "crvena",
    10: "zelena",
    11: "plava",
    12: "ljubicasta",
    13: "braon",
    14: "zuta",
    15: "narandzasta",
    16: "crna",

    17: "crvena",
    18: "zelena",
    19: "plava",
    20: "ljubicasta",
    21: "braon",
    22: "zuta",
    23: "narandzasta",
    24: "crna",

    25: "crvena",
    26: "zelena",
    27: "plava",
    28: "ljubicasta",
    29: "braon",
    30: "zuta",
    31: "narandzasta",
    32: "crna",

    33: "crvena",
    34: "zelena",
    35: "plava",
    36: "ljubicasta",
    37: "braon",
    38: "zuta",
    39: "narandzasta",
    40: "crna",

    41: "crvena",
    42: "zelena",
    43: "plava",
    44: "ljubicasta",
    45: "braon",
    46: "zuta",
    47: "narandzasta",
    48: "crna"
}